<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $bets = [
            'Willian Hill',
            '32Red',
            'MrGreen',
            'Paddypower',
            'Betway',
            'Ladbrokes',
            'Coral',
            'Betfred',
            'Karamba',
            'Betiton',
            'Regalbet',
            'Betathome',
            'Neoebet',
            '888sport',
            'Inerwetten',
            'Admiral',
            'Betsson',
            'Unibet',
            'Mybet',
            'Fansbet',
            'Sunmarket',
            'Happybet',
            'XTIP',
            'Tipico',
            'Izibet',
            'Nordicbet',
            'Titanbet',
            'CashPoint',
            'Bwin',
            'Snai',
            'Sisal',
            'Eurobet',
            'Goldbet',
            'Planetwin365',
            'Lotomatica',
            'Skybet',
            'Coolbet',
            'MegaApuesta',
            'Sportium',
            'Luckia',
            'Yajuego',
            'Codere',
            'Rushbet',
            'Betplay',
            'AlfaBet',
            'BetFair',
            'Zamba',
            'Wplay',
            'Mozzart',
            '365bet',
            'Boylesport',
            'Paddy Power',
            'Marathonbet',
            'William Hill',
            'Bet-at-home',
            'Energybet',
            'Tonybet',
            'BetVictor',
            '10Bet',
            'BetUK',
            'MoPlay',
            'Betregal',
            'MansionBet',
            'Mobilebet',
            'Fun88',
            'Redzonesport',
            'Sportnation',
            'Bethard',
            'Virginbet',
            'Vbet',
            'STS bet',
            'Mobilewins',
            'Opesport',
            'Ohmbet',
            'Lovebet',
            'Voltcasino',
            'Royal Panda',
            'M88',
            'Interbet',
            'Rubybet',
            'Leovegas',
            'Redbet',
            '888',
            'Grosvenor',
            'Mr.green',
            '32redsport',
            'Casumo',
            'Topsport',
            'Aquijuego',
            'Colbet',
            'Rivalo',
            'Mijugada',
            'BetPawa',
            'PremierBet',
            'Bangbet',
            'Soccabet',
            'Supabets',
            'BetBoro',
            'GreatOdds',
            'MyBetAfrica',
            'Betyetu',
            'Betfox',
            'Betplanet',
            'Bolabet',
            'Castlebet',
            'Bwanabet',
            'Galsportbetting',
            'Powerbetting',
            'Sportybet',
            'Eazibet',
            'Bongobongo',
            'Betlion',
            'Yessbet',
            'Mcheza',
            'Sportpesa',
            'Kwikbet',
            'Dafabet',
            'BetVantage',
            'Betking',
            'Jambobet ke',
            'Pitch90bet',
            'Playmaster ke',
            'Betsafe',
            'Betika',
            'Palmsbet',
            'Tipi777',
            'Bet254',
            'Worldsportbetting',
            'Helabet',
            'Betmoto',
            'Melbet',
            'Chezacash',
            'Odibets',
            'Flooks',
            'SBA',
            'Bungabet',
            'Elitebet',
            'Fortebet',
            'Kagwirawo',
            'Beton',
            'Hollywoodbets',
            'Sportingbet',
            'World Sport Betting',
            'Lotto Star',
            'Bet co za',
            'Gbets',
            'Tab Gold',
            'Sunbet',
            'Betxchange',
            'Betyabets',
            'Playbet',
            'Marshalls World of sport',
            'Sportsbet',
            'MG Sport Betting',
            'BetOlimp',
            'Bet9ja',
            'Wazobet',
            'Nairabet',
            'Netbet',
            'Betbonanza',
            'Willaim hill',
            'Ogabet',
            'Merrybet',
            'Surebet247',
            'Accessbet',
            'Saharabet',
            'Actionbet',
            'Bravobet',
            'Winner',
            'Bet251',
            'Vamos',
            'Afrobetting',
            'Harifsport',
            'BET KING',
            'Lalibet',
            'Hulusport',
            'Habeshabets',
            'Winbirr',
            'Anbessabet',
            'Wagerweb',
            'Bookmaker',
            'Betmania',
            'Mybookie',
            'Betonline',
            'Sportsbetting',
            'Heritagesports',
            'Intertops',
            'Vietbet',
            'Draftkings',
            'Gambetdc.dclottery',
            'BETUS',
            'XBET',
            'BETDSI',
            'Abcislands',
            'Betodds',
            'BETPLATINUM',
            'Parxcasino',
            'Cashbet',
            'Sportbet',
            'Looselines',
            'Busr',
            'Tecnobets',
            'Ecuabet',
            'Databet',
            'Teapuesto',
            'Inkabet',
            'Apuestatotal',
            'Betgana',
            'Meridianbet',
            'Lottomatica',
            'Replatz',
            'Betpoint',
            'Betflag',
            'Betaland',
            'Giocodigitale',
            'Scommettendo',
            'Giobet',
            'Betclic',
        ];
        foreach ($bets as $bet) {
            DB::table('bets')->insert([
                'name' => $bet,
            ]);
        }
    }
}
