version: "3.7"

networks:
  bookmaker-network:
    driver: bridge

services:
  bookmaker-nginx:
    restart: always
    container_name: bookmaker-nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - bookmaker-php
    ports:
      - "82:80"
    volumes:
      - "./.:/app/"
    networks:
      - bookmaker-network

  bookmaker-php:
    restart: always
    container_name: bookmaker-php
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - bookmaker-postgres
    env_file:
      - ./.env
    volumes:
      - ".:/app"
    networks:
      - bookmaker-network

  bookmaker-postgres:
    restart: always
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: bookmaker-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=acc_sys
      - POSTGRES_PASSWORD=password
    networks:
      - bookmaker-network
    volumes:
      - "./.data/database/postgres/data:/var/lib/postgresql/data"

  bookmaker-redis:
    restart: always
    build:
        context: .
        dockerfile: .docker/redis/Dockerfile
    container_name: bookmaker-redis
    volumes:
        - ./.data/storage/redis/redis-data:/var/lib/redis
        - ./.data/storage/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_REPLICATION_MODE=master
    ports:
        - "6378:6379"
    networks:
        - bookmaker-network
